"""Standalone HTML report renderer (Jinja2).

Produces a self-contained, styled HTML page using CSS score bars (no image
dependency for the core layout). If figure file names are supplied (relative to
the HTML location) they are embedded as ``<img>`` elements.
"""

from __future__ import annotations

from typing import Dict, Optional

from ..analysis.aggregator import OverallAssessment
from .base import ReportRenderer

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Oratory Analysis Report</title>
<style>
  :root { --good:#2e7d32; --mid:#f9a825; --bad:#c62828; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         margin: 0; background:#f5f6f8; color:#1c1e21; }
  .wrap { max-width: 860px; margin: 0 auto; padding: 32px 20px 64px; }
  header { display:flex; align-items:center; gap:20px; flex-wrap:wrap; }
  .badge { font-size:48px; font-weight:800; width:96px; height:96px; border-radius:16px;
           display:flex; align-items:center; justify-content:center; color:#fff; }
  h1 { font-size:22px; margin:0 0 4px; }
  .meta { color:#606770; font-size:14px; }
  .card { background:#fff; border-radius:12px; padding:20px 24px; margin:20px 0;
          box-shadow:0 1px 3px rgba(0,0,0,.08); }
  .metric { margin:14px 0; }
  .metric .row { display:flex; justify-content:space-between; font-size:14px; margin-bottom:4px; }
  .bar { height:10px; border-radius:6px; background:#e4e6eb; overflow:hidden; }
  .bar > span { display:block; height:100%; border-radius:6px; }
  .summary { color:#606770; font-size:13px; margin-top:4px; }
  .rec { border-left:4px solid var(--mid); padding:8px 16px; margin:16px 0; background:#fffdf5; }
  .rec h3 { margin:0 0 6px; font-size:16px; }
  .drill { background:#eef3ff; border-radius:8px; padding:10px 12px; margin-top:8px; font-size:14px; }
  .tag { display:inline-block; background:#e7f3ff; color:#1565c0; border-radius:12px;
         padding:2px 10px; font-size:12px; margin:2px 4px 2px 0; }
  .tag.warn { background:#fdecea; color:#c62828; }
  img { max-width:100%; border-radius:8px; margin-top:12px; }
  footer { color:#90949c; font-size:12px; text-align:center; margin-top:24px; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="badge" style="background:{{ grade_color }}">{{ a.grade }}</div>
    <div>
      <h1>Oratory Analysis Report</h1>
      <div class="meta">
        Overall <strong>{{ a.overall_score }}/100</strong> &middot; {{ a.label }}<br>
        {{ "%.1f"|format(a.duration_seconds) }}s analyzed &middot;
        {{ a.frames_analyzed }} frames &middot;
        speaker tracked {{ (a.tracking_coverage * 100)|round|int }}% of frames
      </div>
    </div>
  </header>

  <div class="card">
    {% if a.strengths %}<div><strong>Strengths:</strong>
      {% for n in a.strengths %}<span class="tag">{{ a.metrics[n].title }}</span>{% endfor %}
    </div>{% endif %}
    {% if a.weaknesses %}<div style="margin-top:8px"><strong>Focus areas:</strong>
      {% for n in a.weaknesses %}<span class="tag warn">{{ a.metrics[n].title }}</span>{% endfor %}
    </div>{% endif %}
  </div>

  <div class="card">
    <h2 style="margin-top:0">Metric breakdown</h2>
    {% for name, r in metrics_sorted %}
    <div class="metric">
      <div class="row"><span>{{ r.title }}</span><span><strong>{{ r.score|round|int }}</strong>/100</span></div>
      <div class="bar"><span style="width:{{ r.score }}%; background:{{ bar_color(r.score) }}"></span></div>
      <div class="summary">{{ r.summary }}</div>
    </div>
    {% endfor %}
    {% if a.unavailable %}
    <div class="summary" style="margin-top:10px"><em>Not assessed (insufficient visibility):
      {% for name, r in a.unavailable.items() %}{{ r.title }}{% if not loop.last %}, {% endif %}{% endfor %}.</em></div>
    {% endif %}
  </div>

  {% if figures %}
  <div class="card">
    <h2 style="margin-top:0">Charts</h2>
    {% for key, path in figures.items() %}<img src="{{ path }}" alt="{{ key }}">{% endfor %}
  </div>
  {% endif %}

  <div class="card">
    <h2 style="margin-top:0">Recommendations</h2>
    {% if not a.recommendations %}
      <p>No major issues detected — keep refining your delivery.</p>
    {% endif %}
    {% for rec in a.recommendations %}
    <div class="rec">
      <h3>{{ loop.index }}. {{ rec.title }}</h3>
      <div>{{ rec.detail }}</div>
      <div class="drill"><strong>Drill:</strong> {{ rec.drill }}</div>
    </div>
    {% endfor %}
  </div>

  {% if a.notes %}
  <div class="card">
    <h2 style="margin-top:0">Notes &amp; caveats</h2>
    <ul>{% for note in a.notes %}<li>{{ note }}</li>{% endfor %}</ul>
  </div>
  {% endif %}

  <footer>Generated by Oratory Analyzer &middot; landmark tracking via MediaPipe &middot;
  heuristic metrics, not a substitute for a human coach.</footer>
</div>
</body>
</html>
"""


def _bar_color(score: float) -> str:
    if score >= 80:
        return "#2e7d32"
    if score >= 60:
        return "#f9a825"
    return "#c62828"


class HtmlReportRenderer(ReportRenderer):
    extension = "html"

    def __init__(self, figures: Optional[Dict[str, str]] = None) -> None:
        self.figures = figures or {}

    def render(self, assessment: OverallAssessment) -> str:
        from jinja2 import Template

        template = Template(_TEMPLATE)
        metrics_sorted = sorted(
            assessment.metrics.items(), key=lambda kv: kv[1].score
        )
        return template.render(
            a=assessment,
            metrics_sorted=metrics_sorted,
            figures=self.figures,
            grade_color=_bar_color(assessment.overall_score),
            bar_color=_bar_color,
        )
