"""Markdown report renderer (human-readable coaching report)."""

from __future__ import annotations

from typing import List

from ..analysis.aggregator import OverallAssessment
from .base import ReportRenderer


def _score_bar(score: float, width: int = 20) -> str:
    """ASCII progress bar for a 0..100 score."""
    filled = int(round(score / 100.0 * width))
    return "█" * filled + "░" * (width - filled)


class MarkdownReportRenderer(ReportRenderer):
    extension = "md"

    def render(self, assessment: OverallAssessment) -> str:
        lines: List[str] = []
        a = assessment

        lines.append("# Oratory Analysis Report")
        lines.append("")
        lines.append(
            f"**Overall: {a.overall_score}/100 — Grade {a.grade} ({a.label})**"
        )
        lines.append("")
        lines.append(
            f"- Duration analyzed: **{a.duration_seconds:.1f}s** "
            f"({a.frames_analyzed} frames)"
        )
        lines.append(
            f"- Speaker tracked in **{a.tracking_coverage * 100:.0f}%** of frames"
        )
        lines.append("")

        # Headline strengths / focus areas
        if a.strengths:
            titles = ", ".join(a.metrics[n].title for n in a.strengths)
            lines.append(f"**Strengths:** {titles}")
        if a.weaknesses:
            titles = ", ".join(a.metrics[n].title for n in a.weaknesses)
            lines.append(f"**Focus areas:** {titles}")
        lines.append("")

        # Per-metric breakdown
        lines.append("## Metric breakdown")
        lines.append("")
        lines.append("| Metric | Score | | Assessment |")
        lines.append("|---|---:|---|---|")
        for name, r in sorted(a.metrics.items(), key=lambda kv: kv[1].score):
            lines.append(
                f"| {r.title} | {r.score:.0f} | `{_score_bar(r.score)}` | {r.summary} |"
            )
        lines.append("")
        if a.unavailable:
            titles = ", ".join(r.title for r in a.unavailable.values())
            lines.append(f"_Not assessed (insufficient visibility): {titles}._")
            lines.append("")

        # Recommendations
        lines.append("## Recommendations")
        lines.append("")
        if not a.recommendations:
            lines.append("No major issues detected — keep refining your delivery.")
        else:
            for i, rec in enumerate(a.recommendations, 1):
                lines.append(f"### {i}. {rec.title}")
                lines.append("")
                lines.append(rec.detail)
                lines.append("")
                lines.append(f"**Drill:** {rec.drill}")
                lines.append("")

        # Caveats
        if a.notes:
            lines.append("## Notes & caveats")
            lines.append("")
            for note in a.notes:
                lines.append(f"- {note}")
            lines.append("")

        lines.append("---")
        lines.append(
            "_Generated by Oratory Analyzer. Landmark tracking via MediaPipe; "
            "metrics are heuristic aids, not a substitute for a human coach._"
        )
        return "\n".join(lines)
